# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/inventory_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryDialog(object):
    def setupUi(self, InventoryDialog):
        InventoryDialog.setObjectName("InventoryDialog")
        InventoryDialog.resize(500, 300)
        InventoryDialog.setStyleSheet("QDialog {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f0f8ff, stop:1 #e0f7fa);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4caf50;\n"
"    color: white;\n"
"    padding: 12px 24px;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font: bold 14pt Arial;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43a047;\n"
"    box-shadow: 0 3px 6px rgba(0,0,0,0.2);\n"
"}\n"
"\n"
"QLabel {\n"
"    font: bold 14pt Arial;\n"
"    color: #01579b;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 10px;\n"
"    border: 1px solid #90a4ae;\n"
"    border-radius: 8px;\n"
"    background-color: #ffffff;\n"
"    font: 12pt Arial;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #90a4ae;\n"
"    border-radius: 8px;\n"
"    margin-top: 15px;\n"
"    font: bold 16pt Arial;\n"
"    color: #01579b;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 5px 0 5px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(InventoryDialog)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_inventory = QtWidgets.QGroupBox(InventoryDialog)
        self.groupBox_inventory.setObjectName("groupBox_inventory")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_inventory)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_nama = QtWidgets.QLabel(self.groupBox_inventory)
        self.label_nama.setObjectName("label_nama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nama)
        self.namaLineEdit = QtWidgets.QLineEdit(self.groupBox_inventory)
        self.namaLineEdit.setObjectName("namaLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.namaLineEdit)
        self.label_stok = QtWidgets.QLabel(self.groupBox_inventory)
        self.label_stok.setObjectName("label_stok")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_stok)
        self.stokLineEdit = QtWidgets.QLineEdit(self.groupBox_inventory)
        self.stokLineEdit.setObjectName("stokLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stokLineEdit)
        self.label_harga_beli = QtWidgets.QLabel(self.groupBox_inventory)
        self.label_harga_beli.setObjectName("label_harga_beli")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_harga_beli)
        self.hargaBeliLineEdit = QtWidgets.QLineEdit(self.groupBox_inventory)
        self.hargaBeliLineEdit.setObjectName("hargaBeliLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hargaBeliLineEdit)
        self.verticalLayout.addWidget(self.groupBox_inventory)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.simpanButton = QtWidgets.QPushButton(InventoryDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simpanButton.setIcon(icon)
        self.simpanButton.setObjectName("simpanButton")
        self.horizontalLayout.addWidget(self.simpanButton)
        self.batalButton = QtWidgets.QPushButton(InventoryDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batalButton.setIcon(icon1)
        self.batalButton.setObjectName("batalButton")
        self.horizontalLayout.addWidget(self.batalButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(InventoryDialog)
        self.batalButton.clicked.connect(InventoryDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InventoryDialog)

    def retranslateUi(self, InventoryDialog):
        _translate = QtCore.QCoreApplication.translate
        InventoryDialog.setWindowTitle(_translate("InventoryDialog", "Tambah/Edit Inventory"))
        self.groupBox_inventory.setTitle(_translate("InventoryDialog", "Detail Barang"))
        self.label_nama.setText(_translate("InventoryDialog", "Nama Barang:"))
        self.label_stok.setText(_translate("InventoryDialog", "Stok:"))
        self.label_harga_beli.setText(_translate("InventoryDialog", "Harga Beli:"))
        self.simpanButton.setText(_translate("InventoryDialog", "Simpan"))
        self.batalButton.setText(_translate("InventoryDialog", "Batal"))

