# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(450, 250)
        LoginDialog.setStyleSheet("QDialog {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f0f8ff, stop:1 #e0f7fa);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4caf50;\n"
"    color: white;\n"
"    padding: 12px 24px;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font: bold 14pt Arial;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43a047;\n"
"    box-shadow: 0 3px 6px rgba(0,0,0,0.2);\n"
"}\n"
"\n"
"QLabel {\n"
"    font: bold 14pt Arial;\n"
"    color: #01579b;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 10px;\n"
"    border: 1px solid #90a4ae;\n"
"    border-radius: 8px;\n"
"    background-color: #ffffff;\n"
"    font: 12pt Arial;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_username = QtWidgets.QLabel(LoginDialog)
        self.label_username.setObjectName("label_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_username)
        self.usernameLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.label_password = QtWidgets.QLabel(LoginDialog)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.passwordLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.loginButton = QtWidgets.QPushButton(LoginDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login Aplikasi Laundry"))
        self.label_username.setText(_translate("LoginDialog", "Username:"))
        self.label_password.setText(_translate("LoginDialog", "Password:"))
        self.loginButton.setText(_translate("LoginDialog", "Login"))

