# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/order_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderDialog(object):
    def setupUi(self, OrderDialog):
        OrderDialog.setObjectName("OrderDialog")
        OrderDialog.resize(500, 350)
        OrderDialog.setStyleSheet("QDialog {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f0f8ff, stop:1 #e0f7fa);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4caf50;\n"
"    color: white;\n"
"    padding: 12px 24px;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font: bold 14pt Arial;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43a047;\n"
"    box-shadow: 0 3px 6px rgba(0,0,0,0.2);\n"
"}\n"
"\n"
"QLabel {\n"
"    font: bold 14pt Arial;\n"
"    color: #01579b;\n"
"}\n"
"\n"
"QLineEdit, QComboBox {\n"
"    padding: 10px;\n"
"    border: 1px solid #90a4ae;\n"
"    border-radius: 8px;\n"
"    background-color: #ffffff;\n"
"    font: 12pt Arial;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #90a4ae;\n"
"    border-radius: 8px;\n"
"    margin-top: 15px;\n"
"    font: bold 16pt Arial;\n"
"    color: #01579b;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 5px 0 5px;\n"
"}\n"
"\n"
"#totalBiayaLineEdit {\n"
"    font: bold 16pt Arial;\n"
"    color: #4caf50;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(OrderDialog)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_order = QtWidgets.QGroupBox(OrderDialog)
        self.groupBox_order.setObjectName("groupBox_order")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_order)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_pelanggan = QtWidgets.QLabel(self.groupBox_order)
        self.label_pelanggan.setObjectName("label_pelanggan")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_pelanggan)
        self.pelangganComboBox = QtWidgets.QComboBox(self.groupBox_order)
        self.pelangganComboBox.setObjectName("pelangganComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pelangganComboBox)
        self.label_layanan = QtWidgets.QLabel(self.groupBox_order)
        self.label_layanan.setObjectName("label_layanan")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_layanan)
        self.layananComboBox = QtWidgets.QComboBox(self.groupBox_order)
        self.layananComboBox.setObjectName("layananComboBox")
        self.layananComboBox.addItem("")
        self.layananComboBox.addItem("")
        self.layananComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.layananComboBox)
        self.label_berat = QtWidgets.QLabel(self.groupBox_order)
        self.label_berat.setObjectName("label_berat")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_berat)
        self.beratLineEdit = QtWidgets.QLineEdit(self.groupBox_order)
        self.beratLineEdit.setObjectName("beratLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.beratLineEdit)
        self.label_total_biaya = QtWidgets.QLabel(self.groupBox_order)
        self.label_total_biaya.setObjectName("label_total_biaya")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_total_biaya)
        self.totalBiayaLineEdit = QtWidgets.QLineEdit(self.groupBox_order)
        self.totalBiayaLineEdit.setReadOnly(True)
        self.totalBiayaLineEdit.setObjectName("totalBiayaLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.totalBiayaLineEdit)
        self.verticalLayout.addWidget(self.groupBox_order)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.simpanButton = QtWidgets.QPushButton(OrderDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simpanButton.setIcon(icon)
        self.simpanButton.setObjectName("simpanButton")
        self.horizontalLayout.addWidget(self.simpanButton)
        self.batalButton = QtWidgets.QPushButton(OrderDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batalButton.setIcon(icon1)
        self.batalButton.setObjectName("batalButton")
        self.horizontalLayout.addWidget(self.batalButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(OrderDialog)
        self.batalButton.clicked.connect(OrderDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OrderDialog)

    def retranslateUi(self, OrderDialog):
        _translate = QtCore.QCoreApplication.translate
        OrderDialog.setWindowTitle(_translate("OrderDialog", "Buat/Edit Order"))
        self.groupBox_order.setTitle(_translate("OrderDialog", "Detail Order"))
        self.label_pelanggan.setText(_translate("OrderDialog", "Pelanggan:"))
        self.label_layanan.setText(_translate("OrderDialog", "Layanan:"))
        self.layananComboBox.setItemText(0, _translate("OrderDialog", "Cuci Kering"))
        self.layananComboBox.setItemText(1, _translate("OrderDialog", "Setrika"))
        self.layananComboBox.setItemText(2, _translate("OrderDialog", "Cuci Basah"))
        self.label_berat.setText(_translate("OrderDialog", "Berat/Jumlah (kg/item):"))
        self.label_total_biaya.setText(_translate("OrderDialog", "Total Biaya:"))
        self.totalBiayaLineEdit.setText(_translate("OrderDialog", "Rp 0"))
        self.simpanButton.setText(_translate("OrderDialog", "Simpan"))
        self.batalButton.setText(_translate("OrderDialog", "Batal"))

