# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pelanggan_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PelangganDialog(object):
    def setupUi(self, PelangganDialog):
        PelangganDialog.setObjectName("PelangganDialog")
        PelangganDialog.resize(500, 350)
        PelangganDialog.setStyleSheet("QDialog {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f0f8ff, stop:1 #e0f7fa);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4caf50;\n"
"    color: white;\n"
"    padding: 12px 24px;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font: bold 14pt Arial;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43a047;\n"
"    box-shadow: 0 3px 6px rgba(0,0,0,0.2);\n"
"}\n"
"\n"
"QLabel {\n"
"    font: bold 14pt Arial;\n"
"    color: #01579b;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 10px;\n"
"    border: 1px solid #90a4ae;\n"
"    border-radius: 8px;\n"
"    background-color: #ffffff;\n"
"    font: 12pt Arial;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #90a4ae;\n"
"    border-radius: 8px;\n"
"    margin-top: 15px;\n"
"    font: bold 16pt Arial;\n"
"    color: #01579b;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 5px 0 5px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(PelangganDialog)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_pelanggan = QtWidgets.QGroupBox(PelangganDialog)
        self.groupBox_pelanggan.setObjectName("groupBox_pelanggan")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_pelanggan)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_nama = QtWidgets.QLabel(self.groupBox_pelanggan)
        self.label_nama.setObjectName("label_nama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nama)
        self.namaLineEdit = QtWidgets.QLineEdit(self.groupBox_pelanggan)
        self.namaLineEdit.setObjectName("namaLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.namaLineEdit)
        self.label_alamat = QtWidgets.QLabel(self.groupBox_pelanggan)
        self.label_alamat.setObjectName("label_alamat")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_alamat)
        self.alamatLineEdit = QtWidgets.QLineEdit(self.groupBox_pelanggan)
        self.alamatLineEdit.setObjectName("alamatLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.alamatLineEdit)
        self.label_telepon = QtWidgets.QLabel(self.groupBox_pelanggan)
        self.label_telepon.setObjectName("label_telepon")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_telepon)
        self.teleponLineEdit = QtWidgets.QLineEdit(self.groupBox_pelanggan)
        self.teleponLineEdit.setObjectName("teleponLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.teleponLineEdit)
        self.label_email = QtWidgets.QLabel(self.groupBox_pelanggan)
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.emailLineEdit = QtWidgets.QLineEdit(self.groupBox_pelanggan)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.emailLineEdit)
        self.verticalLayout.addWidget(self.groupBox_pelanggan)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.simpanButton = QtWidgets.QPushButton(PelangganDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simpanButton.setIcon(icon)
        self.simpanButton.setObjectName("simpanButton")
        self.horizontalLayout.addWidget(self.simpanButton)
        self.batalButton = QtWidgets.QPushButton(PelangganDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batalButton.setIcon(icon1)
        self.batalButton.setObjectName("batalButton")
        self.horizontalLayout.addWidget(self.batalButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PelangganDialog)
        self.batalButton.clicked.connect(PelangganDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PelangganDialog)

    def retranslateUi(self, PelangganDialog):
        _translate = QtCore.QCoreApplication.translate
        PelangganDialog.setWindowTitle(_translate("PelangganDialog", "Tambah/Edit Pelanggan"))
        self.groupBox_pelanggan.setTitle(_translate("PelangganDialog", "Detail Pelanggan"))
        self.label_nama.setText(_translate("PelangganDialog", "Nama:"))
        self.label_alamat.setText(_translate("PelangganDialog", "Alamat:"))
        self.label_telepon.setText(_translate("PelangganDialog", "Telepon:"))
        self.label_email.setText(_translate("PelangganDialog", "Email:"))
        self.simpanButton.setText(_translate("PelangganDialog", "Simpan"))
        self.batalButton.setText(_translate("PelangganDialog", "Batal"))

